import type { Collection, Piece } from './types';

export const sampleCollections: Collection[] = [
  {
    id: '1',
    title: 'ATELIER NOIR',
    slug: 'atelier-noir',
    season: 'AW 2024',
    description: 'A study in absence. Monochromatic forms, architectural silhouettes, hand-finished seams.',
    story: 'Inspired by the quiet power of shadow and the sculptural quality of negative space, Atelier Noir explores the tension between structure and fluidity. Each piece is cut from Italian wool and Japanese technical fabrics, hand-finished in our Paris workshop. The collection rejects ornamentation in favor of precise tailoring and unexpected volume.',
    heroImage: '/images/collections/atelier-noir-hero.jpg',
    images: [
      '/images/collections/atelier-noir-1.jpg',
      '/images/collections/atelier-noir-2.jpg',
      '/images/collections/atelier-noir-3.jpg',
    ],
    published: true,
    createdAt: '2024-09-15',
  },
  {
    id: '2',
    title: 'TERRE CALME',
    slug: 'terre-calme',
    season: 'SS 2024',
    description: 'Natural fibers meet artisan craft. Earth tones, oversized fits, and honest construction.',
    story: 'Terre Calme is a meditation on materiality. We worked with small mills in Portugal and Japan to source linen, organic cotton, and raw silk. The palette is drawn from clay, sand, and stone. Each garment is washed, dyed, and finished by hand, creating subtle variations that honor the imperfection of craft.',
    heroImage: '/images/collections/terre-calme-hero.jpg',
    images: [
      '/images/collections/terre-calme-1.jpg',
      '/images/collections/terre-calme-2.jpg',
    ],
    published: true,
    createdAt: '2024-03-20',
  },
  {
    id: '3',
    title: 'ARCHIVE ÉDITION',
    slug: 'archive-edition',
    season: 'Archive',
    description: 'Signature pieces from past seasons. Limited availability, enduring design.',
    story: 'Our archive represents the evolution of our design philosophy. These pieces were created with the intention of lasting decades, not seasons. Many are one-of-one or produced in extremely limited runs. Condition varies from pristine to beautifully worn.',
    heroImage: '/images/collections/archive-hero.jpg',
    images: [
      '/images/collections/archive-1.jpg',
      '/images/collections/archive-2.jpg',
      '/images/collections/archive-3.jpg',
      '/images/collections/archive-4.jpg',
    ],
    published: true,
    createdAt: '2023-01-10',
  },
];

export const samplePieces: Piece[] = [
  {
    id: '1',
    name: 'Sculptural Wool Coat',
    slug: 'sculptural-wool-coat',
    designer: 'Atelier',
    collectionId: '1',
    collectionName: 'Atelier Noir',
    price: 2400,
    rentalPrice: 480,
    condition: 'new',
    images: [
      '/images/pieces/wool-coat-1.jpg',
      '/images/pieces/wool-coat-2.jpg',
      '/images/pieces/wool-coat-3.jpg',
    ],
    sizes: ['XS', 'S', 'M'],
    story: 'A statement coat cut from double-face Italian wool. The exaggerated collar and asymmetric closure create dramatic volume while maintaining a clean line. Fully lined in silk twill.',
    category: 'outerwear',
    available: true,
    material: '100% Virgin Wool, Silk Lining',
    care: 'Dry clean only',
  },
  {
    id: '2',
    name: 'Hand-Dyed Linen Shirt',
    slug: 'hand-dyed-linen-shirt',
    designer: 'Atelier',
    collectionId: '2',
    collectionName: 'Terre Calme',
    price: 480,
    rentalPrice: 120,
    condition: 'new',
    images: [
      '/images/pieces/linen-shirt-1.jpg',
      '/images/pieces/linen-shirt-2.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    story: 'Oversized shirt in Portuguese linen, hand-dyed with natural pigments. Each piece is unique. The color shifts subtly from clay to sand depending on light.',
    category: 'tops',
    available: true,
    material: '100% Organic Linen',
    care: 'Machine wash cold, hang dry',
  },
  {
    id: '3',
    name: 'Wide-Leg Wool Trousers',
    slug: 'wide-leg-wool-trousers',
    designer: 'Atelier',
    collectionId: '1',
    collectionName: 'Atelier Noir',
    price: 680,
    condition: 'new',
    images: [
      '/images/pieces/wool-trousers-1.jpg',
      '/images/pieces/wool-trousers-2.jpg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    story: 'High-waisted trousers with a dramatic wide leg. The waistband is faced with grosgrain and finished with a hidden hook closure. Cut from lightweight wool suiting.',
    category: 'bottoms',
    available: true,
    material: '98% Wool, 2% Elastane',
    care: 'Dry clean only',
  },
  {
    id: '4',
    name: 'Silk Slip Dress',
    slug: 'silk-slip-dress',
    designer: 'Atelier',
    collectionId: '2',
    collectionName: 'Terre Calme',
    price: 890,
    rentalPrice: 220,
    condition: 'excellent',
    images: [
      '/images/pieces/silk-dress-1.jpg',
      '/images/pieces/silk-dress-2.jpg',
    ],
    sizes: ['XS', 'S'],
    story: 'Bias-cut slip dress in sand-washed silk. The neckline and hem are hand-rolled. Worn once for an editorial shoot, in excellent condition.',
    category: 'dresses',
    available: true,
    material: '100% Silk Charmeuse',
    care: 'Dry clean recommended',
  },
  {
    id: '5',
    name: 'Leather Tote',
    slug: 'leather-tote',
    designer: 'Atelier',
    collectionId: '1',
    collectionName: 'Atelier Noir',
    price: 1200,
    condition: 'new',
    images: [
      '/images/pieces/leather-tote-1.jpg',
      '/images/pieces/leather-tote-2.jpg',
    ],
    sizes: ['ONE SIZE'],
    story: 'Unstructured tote in vegetable-tanned leather. The interior is unlined. All hardware is brushed brass. Made in Italy.',
    category: 'accessories',
    available: true,
    material: 'Vegetable-Tanned Leather',
    care: 'Condition with leather cream as needed',
  },
  {
    id: '6',
    name: 'Archive Wool Cape',
    slug: 'archive-wool-cape',
    designer: 'Atelier',
    collectionId: '3',
    collectionName: 'Archive Édition',
    price: 1800,
    condition: 'good',
    images: [
      '/images/pieces/wool-cape-1.jpg',
      '/images/pieces/wool-cape-2.jpg',
    ],
    sizes: ['ONE SIZE'],
    story: 'From our 2022 collection. A dramatic cape in charcoal wool with a standing collar. Shows beautiful signs of wear. One-of-one piece.',
    category: 'outerwear',
    available: true,
    material: '100% Merino Wool',
    care: 'Dry clean only',
  },
];
