import type { Collection, Piece } from './types';

export const sampleCollections: Collection[] = [
  {
    id: '1',
    title: 'ATELIER NOIR',
    slug: 'atelier-noir',
    season: 'AW 2024',
    description: 'A study in absence. Monochromatic forms, architectural silhouettes, hand-finished seams.',
    story: 'Inspired by the quiet power of shadow and the sculptural quality of negative space, Atelier Noir explores the tension between structure and fluidity. Each piece is cut from Italian wool and Japanese technical fabrics, hand-finished in our Paris workshop. The collection rejects ornamentation in favor of precise tailoring and unexpected volume.',
    heroImage: '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket1_opt.jpg',
    images: [
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket2_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket3_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket4_opt.jpg',
    ],
    published: true,
    createdAt: '2024-09-15',
  },
  {
    id: '2',
    title: 'TERRE CALME',
    slug: 'terre-calme',
    season: 'SS 2024',
    description: 'Natural fibers meet artisan craft. Earth tones, oversized fits, and honest construction.',
    story: 'Terre Calme is a meditation on materiality. We worked with small mills in Portugal and Japan to source linen, organic cotton, and raw silk. The palette is drawn from clay, sand, and stone. Each garment is washed, dyed, and finished by hand, creating subtle variations that honor the imperfection of craft.',
    heroImage: '/images/turtleneck_sweater_with_intarsia_pattern1_opt.jpg',
    images: [
      '/images/turtleneck_sweater_with_intarsia_pattern2_opt.jpg',
      '/images/turtleneck_sweater_with_intarsia_pattern3_opt.jpg',
    ],
    published: true,
    createdAt: '2024-03-20',
  },
  {
    id: '3',
    title: 'ARCHIVE ÉDITION',
    slug: 'archive-edition',
    season: 'Archive',
    description: 'Signature pieces from past seasons. Limited availability, enduring design.',
    story: 'Our archive represents the evolution of our design philosophy. These pieces were created with the intention of lasting decades, not seasons. Many are one-of-one or produced in extremely limited runs. Condition varies from pristine to beautifully worn.',
    heroImage: '/images/over_sized_faux_leather_pants1_opt.jpg',
    images: [
      '/images/over_sized_faux_leather_pants2_opt.jpg',
      '/images/over_sized_faux_leather_pants3_opt.jpg',
      '/images/over_sized_faux_leather_pants4_opt.jpg',
      '/images/over_sized_faux_leather_pants5_opt.jpg',
    ],
    published: true,
    createdAt: '2023-01-10',
  },
];

export const samplePieces: Piece[] = [
  {
    id: '1',
    name: 'Faux leather mixed with embossed zebra leather Jacket',
    slug: 'faux-leather-zebra-jacket',
    designer: 'LA PIQÛRE',
    collectionId: '1',
    collectionName: 'Atelier Noir',
    price: 2400,
    rentalPrice: 480,
    condition: 'new',
    images: [
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket1_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket2_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket3_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket4_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket5_opt.jpg',
      '/images/faux_leather_mixed_with_embossed_zebra_leather_jacket6_opt.jpg',
    ],
    sizes: ['XS', 'S', 'M'],
    story: 'Striking statement jacket combining faux leather with embossed zebra pattern. Bold textural contrast meets architectural tailoring.',
    category: 'outerwear',
    available: true,
    material: 'Faux Leather, Embossed Zebra Leather',
    care: 'Dry clean only',
    badges: ['new', 'exclusive'],
    colors: [
      { name: 'Black/Zebra', hex: '#1F1A17' },
      { name: 'Tan', hex: '#D9C6A3' }
    ],
    batchNumber: 'LP-AW24-001',
    productionDate: '10/2024',
    materialComposition: [
      { name: 'Faux Leather', percentage: 60, origin: 'Italy' },
      { name: 'Embossed Zebra Leather', percentage: 30, origin: 'Spain' },
      { name: 'Cotton Lining', percentage: 10, origin: 'Portugal' }
    ],
  },
  {
    id: '2',
    name: 'Cropped sleeveless Top with zipper & flat silver studs',
    slug: 'cropped-sleeveless-top-zipper-studs',
    designer: 'LA PIQÛRE',
    collectionId: '2',
    collectionName: 'Terre Calme',
    price: 480,
    rentalPrice: 120,
    condition: 'new',
    images: [
      '/images/cropped_sleeveless_top_with_zipper_&_flat_silver_studs1_opt.jpg',
      '/images/cropped_sleeveless_top_with_zipper_&_flat_silver_studs2_opt.jpg',
      '/images/cropped_sleeveless_top_with_zipper_&_flat_silver_studs3_opt.jpg',
      '/images/cropped_sleeveless_top_with_zipper_&_flat_silver_studs4_opt.jpg',
      '/images/cropped_sleeveless_top_with_zipper_&_flat_silver_studs5_opt.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    story: 'Edgy cropped silhouette featuring front zipper detail and flat silver stud embellishments. Contemporary urban aesthetic.',
    category: 'tops',
    available: true,
    material: 'Premium Cotton Blend',
    care: 'Machine wash cold, hang dry',
    badges: ['new'],
    colors: [
      { name: 'Black', hex: '#1F1A17' },
      { name: 'White', hex: '#FFFFFF' }
    ],
    batchNumber: 'LP-SS24-012',
    productionDate: '09/2024',
  },
  {
    id: '3',
    name: 'Faux leather Cropped Pants',
    slug: 'faux-leather-cropped-pants',
    designer: 'LA PIQÛRE',
    collectionId: '1',
    collectionName: 'Atelier Noir',
    price: 680,
    condition: 'new',
    images: [
      '/images/faux_leather_cropped_pants1_opt.jpeg',
      '/images/faux_leather_cropped_pants2_opt.jpeg',
      '/images/faux_leather_cropped_pants3_opt.jpeg',
      '/images/faux_leather_cropped_pants4_opt.jpeg',
      '/images/faux_leather_cropped_pants5_opt.jpeg',
      '/images/faux_leather_cropped_pants6_opt.jpeg',
      '/images/faux_leather_cropped_pants7_opt.jpeg',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    story: 'High-waisted cropped pants in luxurious faux leather. Modern silhouette with clean lines and statement texture.',
    category: 'bottoms',
    available: true,
    material: 'Premium Faux Leather',
    care: 'Professional leather care recommended',
  },
  {
    id: '4',
    name: 'Cut&sew Distressed knit top',
    slug: 'cutsew-distressed-knit-top',
    designer: 'LA PIQÛRE',
    collectionId: '2',
    collectionName: 'Terre Calme',
    price: 890,
    rentalPrice: 220,
    condition: 'excellent',
    images: [
      '/images/cutsew_distressed_knit_top1_opt.jpeg',
      '/images/cutsew_distressed_knit_top2_opt.jpeg',
      '/images/cutsew_distressed_knit_top3_opt.jpeg',
      '/images/cutsew_distressed_knit_top4_opt.jpeg',
      '/images/cutsew_distressed_knit_top5_opt.jpeg',
    ],
    sizes: ['XS', 'S', 'M'],
    story: 'Artisanal cut and sew construction meets intentional distressing. Each piece is unique with hand-finished details.',
    category: 'tops',
    available: true,
    material: 'Premium Knit Cotton',
    care: 'Hand wash cold, lay flat to dry',
  },
  {
    id: '5',
    name: 'Oversized green faux leather Pants',
    slug: 'oversized-green-faux-leather-pants',
    designer: 'LA PIQÛRE',
    collectionId: '1',
    collectionName: 'Atelier Noir',
    price: 1850,
    condition: 'new',
    images: [
      '/images/oversized_green_faux_leather_pants1_opt.jpg',
      '/images/oversized_green_faux_leather_pants2_opt.jpg',
      '/images/oversized_green_faux_leather_pants3_opt.jpg',
      '/images/oversized_green_faux_leather_pants4_opt.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    story: 'Bold oversized silhouette in striking green faux leather. Statement piece with relaxed, contemporary fit.',
    category: 'bottoms',
    available: true,
    material: 'Premium Faux Leather',
    care: 'Professional leather care recommended',
  },
  {
    id: '6',
    name: 'turtleneck sweater with intarsia pattern',
    slug: 'turtleneck-sweater-intarsia',
    designer: 'LA PIQÛRE',
    collectionId: '2',
    collectionName: 'Terre Calme',
    price: 1800,
    condition: 'new',
    images: [
      '/images/turtleneck_sweater_with_intarsia_pattern1_opt.jpg',
      '/images/turtleneck_sweater_with_intarsia_pattern2_opt.jpg',
      '/images/turtleneck_sweater_with_intarsia_pattern3_opt.jpg',
      '/images/turtleneck_sweater_with_intarsia_pattern4_opt.jpg',
      '/images/turtleneck_sweater_with_intarsia_pattern5_opt.jpg',
      '/images/turtleneck_sweater_with_intarsia_pattern6_opt.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    story: 'Classic turtleneck elevated with intricate intarsia pattern work. Artisanal knitting technique creates dimensional texture.',
    category: 'tops',
    available: true,
    material: '100% Merino Wool',
    care: 'Dry clean only',
    badges: ['low-stock'],
    colors: [
      { name: 'Olive', hex: '#6B7445' },
      { name: 'Burgundy', hex: '#7A231D' }
    ],
    batchNumber: 'LP-SS24-028',
    productionDate: '08/2024',
  },
  {
    id: '7',
    name: 'over sized faux leather pants',
    slug: 'oversized-faux-leather-pants',
    designer: 'LA PIQÛRE',
    collectionId: '3',
    collectionName: 'Archive Édition',
    price: 950,
    condition: 'new',
    images: [
      '/images/over_sized_faux_leather_pants1_opt.jpg',
      '/images/over_sized_faux_leather_pants2_opt.jpg',
      '/images/over_sized_faux_leather_pants3_opt.jpg',
      '/images/over_sized_faux_leather_pants4_opt.jpg',
      '/images/over_sized_faux_leather_pants5_opt.jpg',
      '/images/over_sized_faux_leather_pants6_opt.jpg',
      '/images/over_sized_faux_leather_pants7_opt.jpg',
      '/images/over_sized_faux_leather_pants8_opt.jpg',
      '/images/over_sized_faux_leather_pants9_opt.jpg',
      '/images/over_sized_faux_leather_pants10_opt.jpg',
      '/images/over_sized_faux_leather_pants11_opt.jpg',
      '/images/over_sized_faux_leather_pants12_opt.jpg',
      '/images/over_sized_faux_leather_pants13_opt.jpg',
      '/images/over_sized_faux_leather_pants14_opt.jpg',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    story: 'Relaxed oversized fit in premium faux leather. Versatile wardrobe essential with contemporary edge.',
    category: 'bottoms',
    available: true,
    material: 'Premium Faux Leather',
    care: 'Professional leather care recommended',
  },
];
